'use client';

import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import {
    Save,
    Eye,
    X,
    Plus,
    Globe,
    Tag,
    Image as ImageIcon,
    ChevronDown
} from 'lucide-react';
import ImageUploader from './ImageUploader';
import RichTextEditor from './RichTextEditor';

const BlogFormEditor = ({
    postId = null,
    onSuccess = () => { },
    redirectPath = '/user/blogs'
}) => {
    const { data: session } = useSession();
    const router = useRouter();
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [domains, setDomains] = useState([]);
    const [categories, setCategories] = useState([]);
    const [allTags, setAllTags] = useState([]);
    // Images uploaded during this edit/create session (isolated)
    const [sessionImages, setSessionImages] = useState([]);
    // Optional domain-wide library (collapsed by default)
    const [domainImages, setDomainImages] = useState([]);
    const [domainLibraryLoaded, setDomainLibraryLoaded] = useState(false);
    const [showFeaturedPreview, setShowFeaturedPreview] = useState(false);
    const autosaveTimer = useRef(null);

    const [formData, setFormData] = useState({
        title: '',
        slug: '',
        excerpt: '',
        content: '',
        featuredImage: '',
        status: 'DRAFT',
        domainId: '',
        categoryId: '',
        tags: [],
        metaTitle: '',
        metaDescription: '',
        keywords: ''
    });

    const [newTag, setNewTag] = useState('');

    // Track if user has manually edited SEO fields/slug in this session
    const [metaTouched, setMetaTouched] = useState({ title: false, desc: false, keys: false });
    const [slugTouched, setSlugTouched] = useState(false);
    const lastAutoRef = useRef({ metaTitle: '', metaDescription: '', keywords: '' });

    // Auto-generate SEO metadata when title or excerpt changes
    const autoGeneratedSEO = useMemo(() => {
        const stripHtml = (html) => html ? html.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim() : '';
        const generatedMetaTitle = formData.title.length > 60
            ? formData.title.substring(0, 60)
            : formData.title;

        let baseDesc = formData.excerpt && formData.excerpt.trim().length > 0
            ? formData.excerpt
            : stripHtml(formData.content);
        const generatedMetaDescription = baseDesc.length > 160
            ? baseDesc.substring(0, 160)
            : baseDesc;

        const titleWords = formData.title.toLowerCase().split(' ').filter(word => word.length > 2);
        const tagNames = formData.tags.map(tag => tag.name.toLowerCase());
        const generatedKeywords = [...titleWords, ...tagNames].slice(0, 10).join(', ');

        return {
            metaTitle: generatedMetaTitle,
            metaDescription: generatedMetaDescription,
            keywords: generatedKeywords
        };
    }, [formData.title, formData.excerpt, formData.content, formData.tags]);

    // Auto-sync SEO fields until user edits them; also refresh when title/excerpt/content change
    useEffect(() => {
        setFormData(prev => {
            const next = { ...prev };
            let changed = false;

            // metaTitle
            if (!metaTouched.title) {
                const wasAuto = !prev.metaTitle || prev.metaTitle === lastAutoRef.current.metaTitle;
                if (wasAuto && autoGeneratedSEO.metaTitle && prev.metaTitle !== autoGeneratedSEO.metaTitle) {
                    next.metaTitle = autoGeneratedSEO.metaTitle;
                    changed = true;
                }
            }

            // metaDescription
            if (!metaTouched.desc) {
                const wasAuto = !prev.metaDescription || prev.metaDescription === lastAutoRef.current.metaDescription;
                if (wasAuto && autoGeneratedSEO.metaDescription && prev.metaDescription !== autoGeneratedSEO.metaDescription) {
                    next.metaDescription = autoGeneratedSEO.metaDescription;
                    changed = true;
                }
            }

            // keywords
            if (!metaTouched.keys) {
                const wasAuto = !prev.keywords || prev.keywords === lastAutoRef.current.keywords;
                if (wasAuto && autoGeneratedSEO.keywords && prev.keywords !== autoGeneratedSEO.keywords) {
                    next.keywords = autoGeneratedSEO.keywords;
                    changed = true;
                }
            }

            // Remember last auto values for comparison next run
            lastAutoRef.current = autoGeneratedSEO;
            return changed ? next : prev;
        });
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [autoGeneratedSEO.metaTitle, autoGeneratedSEO.metaDescription, autoGeneratedSEO.keywords]);

    // LocalStorage autosave/restore to prevent content loss on tab/route change
    const draftKey = useMemo(() => {
        const keyParts = ['blog-editor'];
        if (session?.user?.id) keyParts.push(session.user.id);
        if (postId) keyParts.push(`post-${postId}`); else keyParts.push('create');
        return keyParts.join('::');
    }, [postId, session?.user?.id]);

    useEffect(() => {
        try {
            const raw = localStorage.getItem(draftKey);
            if (!raw) return;
            const parsed = JSON.parse(raw);
            // Basic sanity check: at least one of title/content exists
            if (parsed && (parsed.title || parsed.content)) {
                setFormData(prev => ({ ...prev, ...parsed }));
                // Restore session images if any were saved
                if (Array.isArray(parsed.__sessionImages)) {
                    setSessionImages(parsed.__sessionImages);
                }
            }
        } catch { /* ignore */ }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [draftKey]);

    // Fetch initial data
    const fetchInitialData = useCallback(async () => {
        try {
            const promises = [
                fetch('/api/user/domains'),
                fetch('/api/categories'),
                fetch('/api/tags')
            ];

            if (postId) {
                promises.push(fetch(`/api/posts/${postId}`));
            }

            const [domainsRes, categoriesRes, tagsRes, postRes] = await Promise.all(promises);

            // Keep a local reference to domains for later use in create flow
            let domainList = [];

            if (domainsRes.ok) {
                const domainsData = await domainsRes.json();
                domainList = Array.isArray(domainsData) ? domainsData : [];
                setDomains(domainList);
            }

            if (categoriesRes.ok) {
                const categoriesData = await categoriesRes.json();
                setCategories(categoriesData);
            }

            if (tagsRes.ok) {
                const tagsData = await tagsRes.json();
                setAllTags(tagsData);
            }

            // If editing, load post data
            if (postId && postRes?.ok) {
                const postData = await postRes.json();
                setFormData({
                    title: postData.title || '',
                    slug: postData.slug || '',
                    excerpt: postData.excerpt || '',
                    content: postData.content || '',
                    featuredImage: postData.featuredImage || '',
                    status: postData.status || 'DRAFT',
                    domainId: postData.domainId || '',
                    categoryId: postData.categoryId || '',
                    tags: postData.tags || [],
                    metaTitle: postData.metaTitle || '',
                    metaDescription: postData.metaDescription || '',
                    keywords: Array.isArray(postData.keywords)
                        ? postData.keywords.join(', ')
                        : postData.keywords || ''
                });
                // Do not auto-load domain library to avoid showing other posts' images by default
            } else if (domainList.length > 0) {
                // Auto-select first domain for new posts
                setFormData(prev => ({ ...prev, domainId: domainList[0].id }));
                // Don't pre-load domain library to avoid confusion
            }
        } catch (error) {
            console.error('Failed to fetch initial data:', error);
        } finally {
            setLoading(false);
        }
    }, [postId]);

    useEffect(() => {
        fetchInitialData();
    }, [fetchInitialData]);

    const generateSlug = (title) => {
        return title
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/(^-|-$)/g, '');
    };

    const handleTitleChange = (title) => {
        setFormData(prev => ({
            ...prev,
            title,
            slug: slugTouched ? prev.slug : generateSlug(title)
        }));
    };

    const addTag = () => {
        if (newTag.trim() && !formData.tags.some(tag => tag.name === newTag.trim())) {
            const tag = {
                id: `new-${Date.now()}`,
                name: newTag.trim(),
                slug: generateSlug(newTag.trim())
            };
            setFormData(prev => ({
                ...prev,
                tags: [...prev.tags, tag]
            }));
            setNewTag('');
        }
    };

    const removeTag = (tagToRemove) => {
        setFormData(prev => ({
            ...prev,
            tags: prev.tags.filter(tag => tag.id !== tagToRemove.id)
        }));
    };

    const toggleExistingTag = (tag) => {
        const isSelected = formData.tags.some(t => t.id === tag.id);
        if (isSelected) {
            setFormData(prev => ({
                ...prev,
                tags: prev.tags.filter(t => t.id !== tag.id)
            }));
        } else {
            setFormData(prev => ({
                ...prev,
                tags: [...prev.tags, tag]
            }));
        }
    };

    // Image handling functions
    const fetchDomainImages = async (domainId) => {
        if (!domainId) {
            setDomainImages([]);
            return;
        }

        try {
            const response = await fetch(`/api/user/domains/${domainId}/images`);
            if (response.ok) {
                const images = await response.json();
                setDomainImages(images);
                setDomainLibraryLoaded(true);
            }
        } catch (error) {
            console.error('Failed to fetch images:', error);
        }
    };

    const handleImageUploaded = (uploadResult) => {
        const newImage = {
            id: uploadResult.imageId,
            url: uploadResult.imageUrl,
            key: uploadResult.key,
            originalName: uploadResult.originalName || 'Uploaded Image',
            size: uploadResult.size
        };
        setSessionImages(prev => [...prev, newImage]);
        // If no featured image yet, set the first uploaded image as featured automatically
        setFormData(prev => (
            prev.featuredImage ? prev : { ...prev, featuredImage: newImage.url }
        ));
    };

    const handleImageDeleted = (imageId) => {
        setSessionImages(prev => prev.filter(img => img.id !== imageId));

        // Clear featured image if it was the deleted one
        const deletedImage = sessionImages.find(img => img.id === imageId);
        if (deletedImage && formData.featuredImage === deletedImage.url) {
            setFormData(prev => ({ ...prev, featuredImage: '' }));
        }
    };

    const setAsFeaturedImage = (imageUrl) => {
        setFormData(prev => ({ ...prev, featuredImage: imageUrl }));
    };

    // Reset domain library when domain changes (load on demand)
    useEffect(() => {
        setDomainImages([]);
        setDomainLibraryLoaded(false);
        // also clear session images when domain changes to prevent cross-domain confusion
        setSessionImages([]);
    }, [formData.domainId]);

    // Simple URL validator for images
    const isValidImageUrl = (url) => {
        try {
            const urlObj = new URL(url);
            return urlObj.protocol === 'http:' || urlObj.protocol === 'https:';
        } catch {
            return false;
        }
    };

    const handleSave = async (status) => {
        setSaving(true);

        try {
            const method = postId ? 'PUT' : 'POST';
            const url = postId ? `/api/posts/${postId}` : '/api/posts';

            const response = await fetch(url, {
                method,
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    ...formData,
                    categoryId: formData.categoryId || null,
                    status,
                    images: sessionImages.map(img => img.url).filter(Boolean),
                    keywords: typeof formData.keywords === 'string'
                        ? formData.keywords.split(',').map(k => k.trim()).filter(k => k)
                        : formData.keywords
                })
            });

            if (response.ok) {
                const result = await response.json();
                alert(`Post ${status === 'PUBLISHED' ? 'published' : 'saved as draft'} successfully!`);
                onSuccess(result);
                // Clear draft on success
                try { localStorage.removeItem(draftKey); } catch { /* ignore */ }
                router.push(redirectPath);
            } else {
                const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
                const detail = errorData.detail ? `\nDetails: ${errorData.detail}` : '';
                alert(`Failed to save post: ${errorData.error || 'Unknown error'}${detail}`);
            }
        } catch (error) {
            console.error('Failed to save post:', error);
            alert(`Failed to save post: ${error.message}`);
        } finally {
            setSaving(false);
        }
    };

    // Debounced autosave
    useEffect(() => {
        // fields to persist
        const payload = {
            title: formData.title,
            slug: formData.slug,
            excerpt: formData.excerpt,
            content: formData.content,
            featuredImage: formData.featuredImage,
            status: formData.status,
            domainId: formData.domainId,
            categoryId: formData.categoryId,
            tags: formData.tags,
            metaTitle: formData.metaTitle,
            metaDescription: formData.metaDescription,
            keywords: formData.keywords,
            __sessionImages: sessionImages
        };
        if (autosaveTimer.current) clearTimeout(autosaveTimer.current);
        autosaveTimer.current = setTimeout(() => {
            try { localStorage.setItem(draftKey, JSON.stringify(payload)); } catch { /* ignore */ }
        }, 600);
        return () => {
            if (autosaveTimer.current) clearTimeout(autosaveTimer.current);
        };
    }, [draftKey, formData, sessionImages]);

    if (loading) {
        return (
            <div className="min-h-screen bg-black text-white flex items-center justify-center">
                <div className="text-center">
                    <div className="animate-spin rounded-full h-32 w-32 border-b-2 border-yellow-500 mx-auto mb-4"></div>
                    <p className="text-gray-400">Loading...</p>
                </div>
            </div>
        );
    }

    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Main Content */}
                <div className="lg:col-span-2 space-y-6">
                    {/* Title */}
                    <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">
                            Title *
                        </label>
                        <input
                            type="text"
                            value={formData.title}
                            onChange={(e) => handleTitleChange(e.target.value)}
                            placeholder="Enter your blog post title..."
                            className="w-full bg-gray-900 border border-gray-800 rounded-lg px-4 py-3 text-white placeholder-gray-400 focus:outline-none focus:border-yellow-500 text-xl font-semibold"
                        />
                    </div>

                    {/* Slug */}
                    <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">
                            URL Slug
                        </label>
                        <input
                            type="text"
                            value={formData.slug}
                            onChange={(e) => {
                                setSlugTouched(true);
                                setFormData(prev => ({ ...prev, slug: e.target.value }));
                            }}
                            placeholder="auto-generated-from-title"
                            className="w-full bg-gray-900 border border-gray-800 rounded-lg px-4 py-3 text-white placeholder-gray-400 focus:outline-none focus:border-yellow-500"
                        />
                    </div>

                    {/* Excerpt */}
                    <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">
                            Excerpt
                        </label>
                        <textarea
                            value={formData.excerpt}
                            onChange={(e) => setFormData(prev => ({ ...prev, excerpt: e.target.value }))}
                            placeholder="Brief description of your post..."
                            rows={3}
                            className="w-full bg-gray-900 border border-gray-800 rounded-lg px-4 py-3 text-white placeholder-gray-400 focus:outline-none focus:border-yellow-500"
                        />
                    </div>

                    {/* Content - Rich Text Editor */}
                    <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">
                            Content *
                        </label>
                        <RichTextEditor
                            content={formData.content}
                            onChange={(content) => setFormData(prev => ({ ...prev, content }))}
                            placeholder="Write your blog post content here..."
                        />
                    </div>

                    {/* Action Buttons */}
                    <div className="flex items-center space-x-4 pt-6">
                        <button
                            onClick={() => handleSave('DRAFT')}
                            disabled={saving}
                            className="bg-gray-700 hover:bg-gray-600 disabled:bg-gray-800 text-white disabled:text-gray-500 px-6 py-2 rounded-lg flex items-center space-x-2 transition-colors"
                        >
                            <Save className="h-4 w-4" />
                            <span>{saving ? 'Saving...' : 'Save Draft'}</span>
                        </button>
                        <button
                            onClick={() => handleSave('PUBLISHED')}
                            disabled={saving || !formData.title.trim()}
                            className="bg-yellow-500 hover:bg-yellow-600 disabled:bg-gray-800 text-black disabled:text-gray-500 px-6 py-2 rounded-lg flex items-center space-x-2 transition-colors font-semibold"
                        >
                            <Eye className="h-4 w-4" />
                            <span>{saving ? 'Publishing...' : 'Publish'}</span>
                        </button>
                    </div>
                </div>

                {/* Sidebar */}
                <div className="space-y-6">
                    {/* Domain Selection */}
                    <div className="bg-gray-900 rounded-lg border border-gray-800 p-6">
                        <h3 className="text-lg font-bold text-white mb-4 flex items-center">
                            <Globe className="h-5 w-5 mr-2" />
                            Domain
                        </h3>
                        <select
                            value={formData.domainId}
                            onChange={(e) => setFormData(prev => ({ ...prev, domainId: e.target.value }))}
                            className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-white focus:outline-none focus:border-yellow-500"
                        >
                            <option value="">Select domain...</option>
                            {domains.map((domain) => (
                                <option key={domain.id} value={domain.id}>
                                    {domain.domain}
                                </option>
                            ))}
                        </select>
                    </div>

                    {/* Featured Image & Upload */}
                    <div className="bg-gray-900 rounded-lg border border-gray-800 p-6">
                        <h3 className="text-lg font-bold text-white mb-4 flex items-center">
                            <ImageIcon className="h-5 w-5 mr-2" />
                            Images & Featured Image
                        </h3>

                        {/* Image Uploader */}
                        <div className="mb-6">
                            <ImageUploader
                                domainId={formData.domainId}
                                onImageUploaded={handleImageUploaded}
                                currentImages={sessionImages}
                                onImageDeleted={handleImageDeleted}
                                maxImages={3}
                            />
                        </div>

                        {/* Optional Domain Library (collapsed) */}
                        <div className="mb-6">
                            <details className="group">
                                <summary className="cursor-pointer px-3 py-2 bg-gray-800 hover:bg-gray-700 border border-gray-700 rounded flex items-center justify-between text-sm text-gray-200">
                                    <span>Domain Library (optional)</span>
                                    <span className="text-gray-400 group-open:rotate-180 transition-transform">▼</span>
                                </summary>
                                <div className="p-3 border border-t-0 border-gray-700 rounded-b">
                                    {!domainLibraryLoaded ? (
                                        <button
                                            type="button"
                                            onClick={() => fetchDomainImages(formData.domainId)}
                                            disabled={!formData.domainId}
                                            className="bg-gray-700 hover:bg-gray-600 disabled:bg-gray-800 text-white px-4 py-2 rounded"
                                        >
                                            {formData.domainId ? 'Load Domain Images' : 'Select a domain first'}
                                        </button>
                                    ) : (
                                        <>
                                            {domainImages.length === 0 ? (
                                                <div className="text-sm text-gray-400">No images in this domain.</div>
                                            ) : (
                                                <div className="grid grid-cols-3 gap-2">
                                                    {domainImages.slice(0, 12).map((image) => (
                                                        <button
                                                            key={image.id}
                                                            type="button"
                                                            onClick={() => setAsFeaturedImage(image.url)}
                                                            className={`relative group rounded-lg overflow-hidden border-2 transition-all ${formData.featuredImage === image.url
                                                                ? 'border-yellow-500 ring-2 ring-yellow-500/50'
                                                                : 'border-gray-600 hover:border-gray-500'
                                                                }`}
                                                        >
                                                            <Image
                                                                src={image.url}
                                                                alt={image.originalName}
                                                                className="w-full h-16 object-cover"
                                                                width={64}
                                                                height={64}
                                                            />
                                                            <div className="absolute inset-0 bg-black/0 group-hover:bg-black/30 transition-colors flex items-center justify-center">
                                                                <span className="text-white text-xs opacity-0 group-hover:opacity-100 transition-opacity">
                                                                    Set Featured
                                                                </span>
                                                            </div>
                                                            {formData.featuredImage === image.url && (
                                                                <div className="absolute top-1 right-1 bg-yellow-500 text-black rounded-full w-4 h-4 flex items-center justify-center text-xs">
                                                                    ✓
                                                                </div>
                                                            )}
                                                        </button>
                                                    ))}
                                                </div>
                                            )}
                                        </>
                                    )}
                                </div>
                            </details>
                        </div>

                        {/* Featured Image URL Input */}
                        <div className="space-y-3">
                            <label className="block text-sm font-medium text-gray-300">
                                Featured Image URL (or upload above)
                            </label>
                            <input
                                type="url"
                                value={formData.featuredImage}
                                onChange={(e) => setFormData(prev => ({ ...prev, featuredImage: e.target.value }))}
                                placeholder="Enter image URL or upload above..."
                                className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-yellow-500"
                            />

                            {/* Quick Set Featured Image from Session Uploads */}
                            {sessionImages.length > 0 && (
                                <div className="space-y-2">
                                    <label className="block text-sm font-medium text-gray-300">
                                        Or select from uploaded images:
                                    </label>
                                    <div className="grid grid-cols-3 gap-2">
                                        {sessionImages.slice(0, 6).map((image) => (
                                            <button
                                                key={image.id}
                                                type="button"
                                                onClick={() => setAsFeaturedImage(image.url)}
                                                className={`relative group rounded-lg overflow-hidden border-2 transition-all ${formData.featuredImage === image.url
                                                    ? 'border-yellow-500 ring-2 ring-yellow-500/50'
                                                    : 'border-gray-600 hover:border-gray-500'
                                                    }`}
                                            >
                                                <Image
                                                    src={image.url}
                                                    alt={image.originalName}
                                                    className="w-full h-16 object-cover"
                                                    width={64}
                                                    height={64}
                                                />
                                                <div className="absolute inset-0 bg-black/0 group-hover:bg-black/30 transition-colors flex items-center justify-center">
                                                    <span className="text-white text-xs opacity-0 group-hover:opacity-100 transition-opacity">
                                                        Set Featured
                                                    </span>
                                                </div>
                                                {formData.featuredImage === image.url && (
                                                    <div className="absolute top-1 right-1 bg-yellow-500 text-black rounded-full w-4 h-4 flex items-center justify-center text-xs">
                                                        ✓
                                                    </div>
                                                )}
                                            </button>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {/* Featured Image Preview */}
                            {formData.featuredImage && isValidImageUrl(formData.featuredImage) && (
                                <div className="mt-3">
                                    <label className="block text-sm font-medium text-gray-300 mb-2">
                                        Featured Image Preview:
                                    </label>
                                    <Image
                                        src={formData.featuredImage}
                                        alt="Featured"
                                        className="w-full h-32 object-cover rounded-lg border border-gray-700"
                                        onError={() => setShowFeaturedPreview(false)}
                                        width={400}
                                        height={225}
                                    />
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Category */}
                    <div className="bg-gray-900 rounded-lg border border-gray-800 p-6">
                        <h3 className="text-lg font-bold text-white mb-4">Category</h3>
                        <select
                            value={formData.categoryId}
                            onChange={(e) => setFormData(prev => ({ ...prev, categoryId: e.target.value }))}
                            className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-white focus:outline-none focus:border-yellow-500"
                        >
                            <option value="">Select category...</option>
                            {categories.map((category) => (
                                <option key={category.id} value={category.id}>
                                    {category.name}
                                </option>
                            ))}
                        </select>
                    </div>

                    {/* Tags */}
                    <div className="bg-gray-900 rounded-lg border border-gray-800 p-6">
                        <h3 className="text-lg font-bold text-white mb-4 flex items-center">
                            <Tag className="h-5 w-5 mr-2" />
                            Tags
                        </h3>

                        {/* Add new tag */}
                        <div className="flex mb-4">
                            <input
                                type="text"
                                value={newTag}
                                onChange={(e) => setNewTag(e.target.value)}
                                onKeyPress={(e) => e.key === 'Enter' && addTag()}
                                placeholder="Add tag..."
                                className="flex-1 bg-gray-800 border border-gray-700 rounded-l-lg px-3 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-yellow-500"
                            />
                            <button
                                type="button"
                                onClick={addTag}
                                className="bg-yellow-500 hover:bg-yellow-600 text-black px-4 py-2 rounded-r-lg transition-colors"
                            >
                                <Plus className="h-4 w-4" />
                            </button>
                        </div>

                        {/* Selected tags */}
                        <div className="flex flex-wrap gap-2 mb-4">
                            {formData.tags.map((tag) => (
                                <span
                                    key={tag.id}
                                    className="bg-yellow-500 text-black px-3 py-1 rounded-full text-sm flex items-center space-x-2"
                                >
                                    <span>{tag.name}</span>
                                    <button
                                        type="button"
                                        onClick={() => removeTag(tag)}
                                        className="hover:bg-yellow-600 rounded-full p-1 transition-colors"
                                    >
                                        <X className="h-3 w-3" />
                                    </button>
                                </span>
                            ))}
                        </div>

                        {/* Existing tags */}
                        {allTags.length > 0 && (
                            <>
                                <div className="text-sm text-gray-400 mb-2">Select from existing tags:</div>
                                <div className="flex flex-wrap gap-2">
                                    {allTags.map((tag) => {
                                        const isSelected = formData.tags.some(t => t.id === tag.id);
                                        return (
                                            <button
                                                key={tag.id}
                                                type="button"
                                                onClick={() => toggleExistingTag(tag)}
                                                className={`px-3 py-1 rounded text-xs transition-colors ${isSelected
                                                    ? 'bg-yellow-500 text-black'
                                                    : 'bg-gray-800 hover:bg-gray-700 text-gray-300'
                                                    }`}
                                            >
                                                {tag.name} ({tag._count?.posts || 0})
                                            </button>
                                        );
                                    })}
                                </div>
                            </>
                        )}
                    </div>

                    {/* SEO Settings - Collapsible */}
                    <div className="bg-gray-900 rounded-lg border border-gray-800">
                        <details className="group">
                            <summary className="cursor-pointer p-6 flex items-center justify-between hover:bg-gray-800 rounded-lg transition-colors">
                                <h3 className="text-lg font-bold text-white">SEO Settings</h3>
                                <ChevronDown className="text-gray-400 group-open:rotate-180 transition-transform h-5 w-5" />
                            </summary>
                            <div className="px-6 pb-6 space-y-4 border-t border-gray-800 pt-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-300 mb-2">
                                        Meta Title
                                    </label>
                                    <input
                                        type="text"
                                        value={formData.metaTitle}
                                        onChange={(e) => {
                                            if (!metaTouched.title) setMetaTouched(s => ({ ...s, title: true }));
                                            setFormData(prev => ({ ...prev, metaTitle: e.target.value }));
                                        }}
                                        placeholder={autoGeneratedSEO.metaTitle || "SEO title..."}
                                        maxLength={60}
                                        className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-yellow-500"
                                    />
                                    <p className="text-xs text-gray-500 mt-1">{formData.metaTitle.length}/60 characters</p>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-gray-300 mb-2">
                                        Meta Description
                                    </label>
                                    <textarea
                                        value={formData.metaDescription}
                                        onChange={(e) => {
                                            if (!metaTouched.desc) setMetaTouched(s => ({ ...s, desc: true }));
                                            setFormData(prev => ({ ...prev, metaDescription: e.target.value }));
                                        }}
                                        placeholder={autoGeneratedSEO.metaDescription || "SEO description..."}
                                        maxLength={160}
                                        rows={3}
                                        className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-yellow-500"
                                    />
                                    <p className="text-xs text-gray-500 mt-1">{formData.metaDescription.length}/160 characters</p>
                                </div>

                                <div>
                                    <label className="block text-sm font-medium text-gray-300 mb-2">
                                        Keywords
                                    </label>
                                    <input
                                        type="text"
                                        value={formData.keywords}
                                        onChange={(e) => {
                                            if (!metaTouched.keys) setMetaTouched(s => ({ ...s, keys: true }));
                                            setFormData(prev => ({ ...prev, keywords: e.target.value }));
                                        }}
                                        placeholder={autoGeneratedSEO.keywords || "keyword1, keyword2, keyword3..."}
                                        className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-white placeholder-gray-400 focus:outline-none focus:border-yellow-500"
                                    />
                                    <p className="text-xs text-gray-500 mt-1">Separate keywords with commas</p>
                                </div>
                            </div>
                        </details>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default BlogFormEditor;